In [15]:
#source /home/scarlett/github/ipython_notebook/Coding_pythons/myenv/bin/activate
import sys
print(sys.executable)

import torch
import pandas as pd
import numpy as np
import torch.nn as nn

/home/scarlett/github/Coding_pythons/newenv/bin/python


To install new packages:
- source /home/scarlett/github/Coding_pythons/newenv/bin/activate
- pip install <package_name>
- pip list
- import <package_name>
- deactivate

## Deep learning
- deep learning is everywhere:
    - language translation
    - self-driving cars
    - medical diagnostics
    - chatbots

- used on multiple data types: images, text and audio
- traditional machine learning: relies on hand-crafted feature engineering
- deep learning: enables feature learning from raw data

## What is deep learning?
- An architecture of network consists of input, hidden layers and output
- A network can have one or many hidden layers
- Require 100K data
- pytorch supports tabular data, also unstructral data like image (torchvision), audio data (torchaudio), text data (torchtext)
- deep learning often requires a GPU, which, compard to a CPU can offer: parallel computing capabilities, faster training times and better performance
- tensors are multidimensional representations of their elements

#### make tensor: load from list

In [4]:
lst = [[1,2,3],[4,5,6],[7,8,9]]
tensor = torch.tensor(lst)
tensor 

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [7]:
tensor.shape

torch.Size([3, 3])

In [8]:
tensor.dtype

torch.int64

In [9]:
tensor.device

device(type='cpu')

#### load from NumPy array

In [5]:
array = [[1,2,3],[4,5,6],[7,8,9]]
np_array = np.array(array)
np_tensor = torch.from_numpy(np_array)

### tensor operations - most numpy array operations can be performedon PyTorch tensors

In [14]:
tensor + np_tensor

tensor([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]])

In [13]:
tensor * np_tensor

tensor([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]])

## neural net
### basic two layer NN without hidden layer
- first layer: input, second layer: linear layer
- each linear layer has a .weight and .bias associated
- nn.linear performs
    - when input_tensor is passed to linear_layer, the linear operation performed is matrix multiplication of input_tensor and the weights, followed by adding in the bias
    - input X, weights W0, bias b0 --> y0 = W0 * X +b0; in pytorch: output = W0 * input + b0
    - initially, when we call nn.Linear(), weights and biases are initialized randomly, so they are not yet useful
    - we have to tune these weights and biases
- two-layer network summary:
    - took 1 by 3 input as the first layer (1 linear layer with specific arguments as the second layer, and retured a 1 by 2 output)
    - linear layers have connections (or arrows) between each input and output neuron, making them fully connected
        - networks with only linear layers are called: "fully connected networks"
        - each neuron in one layer is connected to each neuron in the next layer

In [20]:
## create input_tensor with 3 features
input_tensor = torch.tensor([[0.3471, 0.4547, -0.2356]], dtype=torch.float32)

## define first linear layer ( a linear layer takes an input, applies a linear fxn, and returns output)
linear_layer = nn.Linear(in_features=3, out_features=2)

## pass input through linear layer
output = linear_layer(input_tensor)
print(output)

tensor([[ 0.0560, -0.6962]], grad_fn=<AddmmBackward0>)


In [21]:
linear_layer.weight

Parameter containing:
tensor([[-0.2942, -0.0729, -0.2760],
        [-0.3467, -0.1545, -0.2645]], requires_grad=True)

In [22]:
linear_layer.bias

Parameter containing:
tensor([ 0.1262, -0.5679], requires_grad=True)

### Multi-layer model: Stacking layers with nn.Sequential()
- this model takes input, passes it to each linear layer in sequence, and returns output
    - the first layer takes input with 10 features, and output with a tensor with 18 features
    - the second layer takes input with 18 features, and output with a tensor with 20 features
    - the third layer takess input with 20 featuresl and output with a tensor with 5 features
- output is not linear until each layer has tuned weights and biases

In [23]:
model = nn.Sequential(
    nn.Linear(10,18), 
    nn.Linear(18,20), 
    nn.Linear(20,5))

In [24]:
# make a input_tensor with ten features (neurons)
input_tensor = torch.rand(1,10)
input_tensor

tensor([[0.8991, 0.5175, 0.2633, 0.3706, 0.5805, 0.0322, 0.7388, 0.3716, 0.0867,
         0.3902]])

In [25]:
# pass input_tensor through model
output = model(input_tensor)

#### In this exercise, you will implement a small neural network containing two linear layers. The first layer takes an eight-dimensional input, and the last layer outputs a one-dimensional tensor.

In [26]:
input_tensor = torch.Tensor([[2, 3, 6, 7, 9, 3, 2, 1]])

# Implement a small neural network with exactly two linear layers
model = nn.Sequential(nn.Linear(8,5),
                      nn.Linear(5,1)
                     )

output = model(input_tensor)
print(output)

tensor([[-0.4597]], grad_fn=<AddmmBackward0>)


### Activation functions
- 